Repository openedx/xblock-lti-consumer, pull requests merged in 2020-07, with the labels that each got.

#77 BD-02 BD-03 Add support for LTI embeds in course tabs and elsewhere
  Makefile
  lti_consumer/exceptions.py
  lti_consumer/lti.py
  lti_consumer/lti_1p1/README.rst
  lti_consumer/lti_1p1/__init__.py
  lti_consumer/lti_1p1/consumer.py
  lti_consumer/lti_1p1/contrib/__init__.py
  lti_consumer/lti_1p1/contrib/django.py
  lti_consumer/lti_1p1/contrib/tests/__init__.py
  lti_consumer/lti_1p1/contrib/tests/test_django.py
  lti_consumer/lti_1p1/exceptions.py
  lti_consumer/lti_1p1/oauth.py
  lti_consumer/lti_1p1/tests/__init__.py
  lti_consumer/lti_1p1/tests/test_consumer.py
  lti_consumer/lti_1p1/tests/test_oauth.py
  lti_consumer/lti_xblock.py
  lti_consumer/outcomes.py
  lti_consumer/tests/unit/test_lti.py
  lti_consumer/tests/unit/test_lti_consumer.py
  lti_consumer/tests/unit/test_utils.py
  requirements/travis.in
  setup.py
Labels: needs triage, open-source-contribution

#85 [BD-2] [BB-2612]: Add ADR to define LTI Plugin architecture implementation
  docs/decisions/0001-lti-extensions-plugin.rst
Labels: blended, needs triage

#87 [BD-24] [TNL-7316] Implement context claim on LTI 1.3
  README.rst
  lti_consumer/lti_1p3/constants.py
  lti_consumer/lti_1p3/consumer.py
  lti_consumer/lti_1p3/tests/test_consumer.py
  lti_consumer/lti_xblock.py
  lti_consumer/tests/unit/test_lti_xblock.py
  lti_consumer/tests/unit/test_outcomes.py
  setup.py
Labels: engineering review, open-source-contribution

#90 [BD-18] remove nose footprints from the project
  requirements/base.txt
  requirements/django.txt
  requirements/test.in
  requirements/test.txt
  requirements/tox.txt
  requirements/travis.txt
Labels: blended, needs triage
