Repository openedx/xblock-lti-consumer, pull requests merged in 2020-10, with the labels that each got.

#92 [BD-24] [TNL-7318]: LTI AGS Implementation - LineItem Service
  lti_consumer/admin.py
  lti_consumer/lti_1p3/ags.py
  lti_consumer/lti_1p3/constants.py
  lti_consumer/lti_1p3/consumer.py
  lti_consumer/lti_1p3/exceptions.py
  lti_consumer/lti_1p3/extensions/rest_framework/parsers.py
  lti_consumer/lti_1p3/extensions/rest_framework/permissions.py
  lti_consumer/lti_1p3/extensions/rest_framework/renderers.py
  lti_consumer/lti_1p3/extensions/rest_framework/serializers.py
  lti_consumer/lti_1p3/tests/extensions/rest_framework/test_permissions.py
  lti_consumer/lti_1p3/tests/test_ags.py
  lti_consumer/lti_1p3/tests/test_consumer.py
  lti_consumer/migrations/0002_ltiagslineitem.py
  lti_consumer/models.py
  lti_consumer/plugin/urls.py
  lti_consumer/plugin/views.py
  lti_consumer/tests/unit/plugin/test_views_lti_ags.py
  lti_consumer/tests/unit/test_lti_xblock.py
  lti_consumer/tests/unit/test_models.py
  lti_consumer/utils.py
  requirements/base.in
  requirements/base.txt
  requirements/django.txt
  requirements/test.txt
  requirements/travis.txt
  test_settings.py
  test_urls.py
Labels: blended, needs triage

#111 TNL-7608 - Add Note about ngrok usage.
  README.rst
Labels: needs triage, open-source-contribution

#89 [BD-2][TNL-7315] BB-2612: Add ADR for LTI 1.3 variable definition
  docs/decisions/0002-lti-1p3-variables.rst
Labels: blended, engineering review

#108 [BD-24] Implement LTI AGS Score Publish Service and Results
  .gitignore
  lti_consumer/lti_1p3/constants.py
  lti_consumer/lti_1p3/extensions/rest_framework/parsers.py
  lti_consumer/lti_1p3/extensions/rest_framework/permissions.py
  lti_consumer/lti_1p3/extensions/rest_framework/renderers.py
  lti_consumer/lti_1p3/extensions/rest_framework/serializers.py
  lti_consumer/lti_1p3/tests/extensions/rest_framework/test_permissions.py
  lti_consumer/migrations/0003_ltiagsscore.py
  lti_consumer/models.py
  lti_consumer/plugin/views.py
  lti_consumer/tests/unit/plugin/test_views_lti_ags.py
  lti_consumer/tests/unit/test_models.py
Labels: blended, engineering review
